# 更新文件地址，每次启动都会检查更新
metadata = "http://example.com/metadata.toml"

# 版本号，目前仅作为标识作用
version = 0

[network]
# 是否强制切换到quic，只走UDP协议
quic = false
# 是否忽略证书错误
ignore_invalid_cert = true

[[groups]]

# 锚点文件/文件夹，用于定位工作目录
# 如果搜索到该文件夹，则锚点目录为该文件夹
# 如果搜索到该文件，则锚点目录为该文件所在的文件夹
anchor = "Minecraft.jar"

# 工作目录，相对于锚点文件夹
root = "mods"

# 是否包含子文件夹中的文件
recursive = false

# 是否为镜像模式
# 镜像模式下会处理目录中不在列表内的文件
mirror = true

# 是否删除不在列表内的文件
# 如果不删除但是镜像模式，则会将这些文件的后缀名改为 .原后缀.disabled
delete = false

# 组规则
# 用于指定将什么样的文件对应于该组中
pattern = '^.+\.jar$'

# 每一个文件规则如果有多个规则，关系为和（AND）
[[groups.files]]
# 如果有 name 字段，则优先使用文件名进行完全匹配
name = "OreExcavation.jar"
url = "https://example.com/files/OreExcavation.jar"

[[groups.files]]
# 如果有 mod_id 字段，则使用 mod_id 和 mod_version 进行匹配
# 若使用此种定义方式，mod_id为必需字段，mod_version为可选字段 
mod_id = "immersiveengineering"
mod_version = "1.18.2-8.4.0-161"
url = "https://example.com/files/immersiveengineering-1.18.2-8.4.0-161.jar"

[[groups.files]]
# 如果有 name_pattern 字段，则使用正则表达式进行文件名匹配
name_pattern = '^lucky_hat-1.0.\d.jar$'
url = "https://example.com/files/lucky_hat-1.0.2.jar"

[[groups.files]]
# 如果有 sha256 字段，则使用 sha256 进行匹配
# 对于远程 metadata（也就是toml）文件，如果服务器存在 filename.sha256 文件，则会检测 sha256 是否一致。
# 如 http://example.com/metadata.toml.sha256
# 如果你的服务器支持，也可以通过设置自定义 HTTP Response Header：`x-checksum-sha256` 和 `x-sha256`

# 这里的 name 不是必须的，但 toml 里仍然可以写注释，比 json 好得多不是嘛？
# name = "tac-0.3.10.1-1.18.2.jar"
sha256 = "24232e4500aa3385923ad3947bec8443dc4f04c9cf17c2f94521dcfcd3a1bc20"
url = "https://example.com/files/tac-0.3.10.1-1.18.2.jar"
