# 更新文件地址，每次启动都会检查更新
metadata = "http://example.com/metadata.toml"

# 版本号，每次更新后请增加此版本号以确保更新生效
version = 0

[[groups]]

# 锚点文件/文件夹，用于定位工作目录
# 如果搜索到该文件夹，则锚点目录为该文件夹
# 如果搜索到该文件，则锚点目录为该文件所在的文件夹
anchor = "DeceasedCraft.jar"

# 工作目录，相对于锚点文件夹
root = "mods"

# 是否包含子文件夹中的文件
recursive = false

# 是否为镜像模式
# 镜像模式下会处理目录中不在列表内的文件
mirror = true

# 是否删除不在列表内的文件
# 如果不删除但是镜像模式，则会将这些文件的后缀名改为 .jar.disabled
delete = false

# 组规则
# 用于指定将什么样的文件对应于该组中
pattern = '^.+\.jar$'

[[groups.files]]
# 如果有 name 字段，则优先使用文件名进行完全匹配
name = "[矿石挖掘] OreExcavation-1.10.162.jar"
url = "https://example.com/files/OreExcavation-1.10.162.jar"

[[groups.files]]
# 如果有 mod_id 字段，则使用 mod_id 和 mod_version 进行匹配
mod_id = "immersiveengineering"
mod_version = "1.18.2-8.4.0-161"
url = "https://example.com/files/immersiveengineering-1.18.2-8.4.0-161.jar"

[[groups.files]]
# 如果有 name_pattern 字段，则使用正则表达式进行文件名匹配
# 有该字段时会无视 name 字段
name_pattern = '^lucky_hat-1.0.\d.jar$'
url = "https://example.com/files/JustEnoughItems-latest.jar"