metadata = "http://example.com/metadata.toml"
version = 1

[self_update]
url = "http://example.com/mc_simple_patcher.exe"
[[self_update.patches]]
url_patch = "https://example.com/mc_simple_patcher.exe.v0.2.5.patch"
sha256_src = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
keep_src = true

[network]
quic = true
ignore_invalid_cert = false
timeout = 10
retry = 10

# <必须> 只有这个表会被遍历并替换成对应的 groups 表
[[generate]]
# 锚点文件/文件夹，用于定位工作目录
# 一般可以设置为 Minecraft 主 jar 文件
anchor = "Minecraft.jar"

# 工作目录，相对于锚点文件夹
root = "mods"

# 用于匹配文件的正则表达式
# 记得使用单引号取消反义
pattern = '^.+\.jar$'

# 是否包含子文件夹中的文件
recursive = false

# URL 基础路径，用于生成下载链接
# 每个文件的下载连接将被生成为 "{url_base}{name}"
url_base = "http://example.com/mods/"

# 以下选项控制生成的配置中包含哪些字段
name = true          # 是否包含文件名
mod_id = false       # 是否包含 mod_id（对于 JAR 文件）
mod_version = false  # 是否包含 mod_version（对于 JAR 文件）
sha256 = true        # 是否计算并包含文件的 SHA256 哈希值

# [可选] 如果使用patch，这个部分将被注入到相应的文件的条目下
[[patches]]
# <必须> 这个 patch 条目将被注入到这个 SHA256 的文件规则条目下
sha256_dst = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

# <必须> BSDIFF4-format 补丁 URL 路径
url_patch = "https://example.com/files/tac-0.3.10.1-1.18.2.jar.v1.patch"

# <必须> 源文件的 SHA256 哈希值（64 字符十六进制字符串）
sha256_src = "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"

# [可选] 补丁后是否保留源文件。默认为 true
# 如果保留，则其将被重命名为 <filename>.backup
keep_src = true